name: Check Format

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Run format
      run: npm run format-check

  build-image:
     runs-on: ubuntu-latest
     needs: check-format
     steps:
        - uses: actions/checkout@v4
        - name: Build the Docker image
          run: docker build . --file Dockerfile --tag philipphofer-website:$(date +%s)

